### ISSUE TITLE
Wrong example for BinaryPayloadBuilder

### ISSUE THREAD

**Issue by mindmixer** [bashwork/pymodbus#104]
In the [Modbus Payload Server Context Building Example](https://github.com/bashwork/pymodbus/blob/master/examples/common/modbus-payload-server.py) you can find the following part of code:
```Python
block = ModbusSequentialDataBlock(1, builder.to_registers())
store = ModbusSlaveContext(di = block, co = block, hr = block, ir = block)
context = ModbusServerContext(slaves=store, single=True)
```
but the `builder` object (the instance of `BinaryPayloadBuilder` class) doesn't have the `to_registers` method.

**Comment by OptrixAU** [comment]
Why was this closed? Any explaination?
