### ISSUE TITLE
StartSerialServer Error when trying to use a different Framer

### ISSUE THREAD

**Issue by pmjfontes** [bashwork/pymodbus#123]
Hi Guys,
I am trying to use the Pymobus to create an RTU Serial Slave device, I got into an error when trying to set the parameter framer=ModbusRtuFramer in the StartSerialServer call.

```
server = ModbusSerialServer(context, framer, identity, **kwargs)
TypeError: __init__() got multiple values for keyword argument 'framer'
```

I assume this is happening because the StartSerialServer, calls the ModbusSerialServer with the framer parameter and it also sends it in the **kwargs to the class __init__.

As workaround I am calling:

```
server = ModbusSerialServer(context=app.context, framer=ModbusRtuFramer, port=serial, baudrate=baud, stopbits=stopbits, parity=parity, timeout=0.005)
server.serve_forever()
```

**Comment by glebv** [comment]
+1, the same issue
