### ISSUE TITLE
Some help for installing modbuspy on ubuntu

### ISSUE THREAD

**Issue by magnusm6** [bashwork/pymodbus#59]
I hope someone can help me because I am not a python expert. I couldn't install modbuspy package on a Windows machine so I'm planning to install ubuntu on a virtual machine. My questions are:

1. Is that ok if I install ubuntu 14.04 .1lts?
2. Is that ok if I use python 2.7.8?

thanks in advance

**Comment by bashwork** [comment]
Both of those are fine. When you are installing, please install from github and not pip. The dependencies can however be installed from pip.

**Comment by MartinBorg** [comment]
Btw. pymodbus 1.2.0 is available directly in Ubuntu: http://packages.ubuntu.com/search?keywords=pymodbus&searchon=names&suite=all
