### ISSUE TITLE
Read Device Information using ModbusTcpClient

### ISSUE THREAD

**Issue by alexkaskasoli** [bashwork/pymodbus#77]
I've looked at the docs for the ModbusTcpClient, there's functions to read coils and registers but I couldn't see one for what Modbus calls "Function 43/14: Read Device Information"

Can you read the device information using a ModbusTcpClient object?

**Comment by xvart** [comment]
no support for that as yet, and I'm busy with other things at work at the moment so won't be able to add anything for a while

**Comment by alexkaskasoli** [comment]
Thanks for the update!
Pymodbus is great though, I will perhaps try to implement RDI myself and get back to you if I do.

**Comment by bashwork** [comment]
All of the modbus spec is implemented. These requests are in the mei_messages import.
