### ISSUE TITLE
Function Read Discrete Inputs

### ISSUE THREAD

**Issue by clafouti2104** [bashwork/pymodbus#86]
Hi,

I'm trying to use the modbus function 2 (read discrete inputs) but the response received is not correct. 
Is there a way to get the non formatted response (no True/False response but the 0x..)?

Thanks

from pymodbus.client.sync import ModbusTcpClient as ModbusClient

import logging
logging.basicConfig()
log = logging.getLogger()
log.setLevel(logging.DEBUG)

client = ModbusClient('172.22.8.9', port=502)
client.connect()
rq = client.read_discrete_inputs(4090, 10)
print rq
print rq.bits

**Comment by xinthose** [comment]
This is what I use:

	# registers --- 40000
	client.write_register(0,7)
	reg_result = client.read_holding_registers(0x00,4,unit=1)
	print "read_holding_registers: " + str(reg_result.registers)
	reg_result_0 = reg_result.registers[0]	# single result
	print reg_result_0
